// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function Layout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



// app/layout.tsx

import { ReactNode } from 'react';
import './globals.css'; // Import global styles if you have any
import { Button } from "@/components/ui/button";
import Link from 'next/link';
import { Home, BookOpen } from 'lucide-react';

export const metadata = {
  title: 'Sequence Learning',
  description: 'Learn about sequences in a fun way!',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-background flex flex-col">
          <header className="border-b">
            <div className="container mx-auto px-4 py-4 flex justify-between items-center">
              <h1 className="text-2xl font-bold text-primary">Sequence Learning</h1>
              <nav>
                <ul className="flex space-x-4">
                  <li>
                    <Link href="/">
                      <Button variant="ghost">
                        <Home className="mr-2 h-4 w-4" />
                        Home
                      </Button>
                    </Link>
                  </li>
                  <li>
                    <Link href="/learn">
                      <Button variant="ghost">
                        <BookOpen className="mr-2 h-4 w-4" />
                        Learn
                      </Button>
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
          </header>
          <main className="flex-grow container mx-auto px-4 py-8">
            {children}
          </main>
          <footer className="border-t">
            <div className="container mx-auto px-4 py-4 text-center text-sm text-muted-foreground">
              © 2023 Sequence Learning. All rights reserved.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}


